### PR TITLE
fixing PR after directory reshuffle on master

### PR DESCRIPTION
**Pull request by slayoo**

### CODE REVIEW

**Comment by olebole** [comment]
Hmm, what shall I do with this? Shall I rebase gnudatalanguage/gdl#6 for the new directory structure?

**Comment by slayoo** [comment]
https://github.com/olebole/gdl/pull/1 :)

**Comment by slayoo** [comment]
the above pull request (to your fork) should fix the conflict in this PR

**Comment by olebole** [comment]
I just rebased, which could be done automatically. `git rebase master` after an update.

**Comment by olebole** [comment]
I would start from scratch, and then only import the "gdl" submodule. No glue how to do this directly in github. On the command line, you need "git-svn".
I could do it as well if you give me temporary write access to the repo.

**Comment by slayoo** [comment]
thank you! Here it is - a fresh one: https://github.com/gnudatalanguage/gdl

(the previous one is now renamed at https://github.com/gnudatalanguage/gdl.off)

**Comment by olebole** [comment]
Will take a while; it needs to convert 4000 commits...

**Comment by slayoo** [comment]
Thank you Ole! After it's done, I'll set up back Travis in the new repo

**Comment by olebole** [comment]
It will however take quite some time... now I have ~1000 of 4000 commits... with one error on sourceforge's side.

**Comment by slayoo** [comment]
Thanks again for help with it.
P.S. Here is a first "successful" Travis build and testsuite run: https://travis-ci.org/gnudatalanguage/ci-tests/builds/362062807
Quite some TODOs still inside the travis file, but should be enough to start with

**Comment by olebole** [comment]
OK, it took a while (and two attempts, since the first was somehow incomplete), but [gnudatalanguage/gdl](https://github.com/gnudatalanguage/gdl) is filled. Could you check and confirm?
What about **gdlde**? shall it be saved as well?

**Comment by slayoo** [comment]
Thank you! I will add Travis file now.
Perhaps let's make a separate repo for it? I've added it and granted you write permissions - if possible, could you please populate it with the files from SF: https://github.com/gnudatalanguage/gdlde

Also, let me close this issue and suggest moving discussions to: https://github.com/orgs/gnudatalanguage/teams/gdldevs

**Pull request closed without merging**
